# Generated by Django 5.1.5 on 2025-07-02 07:59

import django.db.models.deletion
import tienda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('foto_destacada', models.ImageField(blank=True, help_text='Foto destacada para la categoría (PNG, JPG o JPEG)', null=True, upload_to='categorias/', validators=[tienda.models.validar_imagen_png_jpg])),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('tipo_fragancia', models.CharField(blank=True, choices=[('citrico', 'Cítrico'), ('floral', 'Floral'), ('amaderado', 'Amaderado'), ('oriental', 'Oriental'), ('fresco', 'Fresco'), ('dulce', 'Dulce'), ('acuatico', 'Acuático')], help_text='Solo aplica si es un perfume', max_length=20, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=tienda.models.nombre_foto_producto, validators=[tienda.models.validar_imagen_png])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.genero')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.marca')),
            ],
        ),
    ]
